[project]
name = "blender-expert"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.3"
dependencies = [
    "mcp[cli]>=1.9.3",
    "openai>=1.86.0",
]
